apiVersion: apps/v1
kind: Deployment
metadata:
  name: fregservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fregservice
  template:
    metadata:
      labels:
        app: fregservice
    spec:
      containers:
      - name: fregservice
        image: johannesdigdir/freg_service:0bb84a11b33ea2f3528f951dabd7809450c77a6e
        ports:
        - containerPort: 5000