apiVersion: apps/v1
kind: Deployment
metadata:
  name: fregservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fregservice
  template:
    metadata:
      labels:
        app: fregservice
    spec:
      containers:
      - name: fregservice
        image: johannesdigdir/freg_service:5184f67c9fb9ae6f66fd46c81b2c5ec527e32592
        ports:
        - containerPort: 5000