apiVersion: apps/v1
kind: Deployment
metadata:
  name: fregservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fregservice
  template:
    metadata:
      labels:
        app: fregservice
    spec:
      containers:
      - name: fregservice
        image: johannesdigdir/freg_service:55878569d5f3958ead7dc725ca338273676236a0
        ports:
        - containerPort: 5000