apiVersion: apps/v1
kind: Deployment
metadata:
  name: fregservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fregservice
  template:
    metadata:
      labels:
        app: fregservice
    spec:
      containers:
      - name: fregservice
        image: johannesdigdir/freg_service:9a57c0c1798e89d63cc6993fa0817c8425e3766a
        ports:
        - containerPort: 5000